name: os_release
description: Reads the os-release file on Linux Distributions and makes accessing the contents of the file easy.
version: 0.2.1
repository: https://github.com/alastairlundy/os_release_dart
issue_tracker: https://github.com/alastairlundy/os_release_dart/issues/

platforms:
  linux:

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:


dev_dependencies:
  checks: ^0.3.0
  lints: ^3.0.0
  test: ^1.24.0
